# Generated by Django 3.2.6 on 2021-12-29 05:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agreement', '0002_auto_20211229_1015'),
    ]

    operations = [
        migrations.CreateModel(
            name='payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_year', models.CharField(choices=[('2022', '2022'), ('2023', '2023'), ('2024', '2024'), ('2025', '2025')], max_length=50)),
                ('payment_month', models.CharField(choices=[('January', 'January'), ('February', 'February'), ('March', 'March'), ('April', 'April'), ('May', 'May'), ('June', 'June'), ('Jule', 'Jule'), ('August', 'August'), ('September', 'September'), ('October', 'October'), ('November', 'November'), ('December', 'December')], max_length=100)),
                ('discount_status', models.CharField(choices=[('Active', 'Active'), ('Passive', 'Passive')], default='Passive', max_length=15)),
                ('discount_reason', models.CharField(default='No', max_length=100)),
                ('discount_size', models.PositiveIntegerField(default=0)),
                ('payment_date', models.DateField()),
                ('must_pay', models.PositiveIntegerField(default=0)),
                ('cashier', models.CharField(max_length=100)),
                ('in_hand', models.PositiveIntegerField(default=0)),
                ('bank', models.PositiveIntegerField(default=0)),
                ('card', models.PositiveIntegerField(default=0)),
                ('payed', models.PositiveIntegerField(default=0)),
                ('rest_money', models.PositiveIntegerField(default=0)),
                ('agreement', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='agreement.agreement')),
                ('course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='agreement.course')),
                ('student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='agreement.student')),
                ('teacher', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='agreement.teacher')),
            ],
        ),
    ]
